//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Examen_AgenciaViviendas.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class VENta
    {
        public int Codigo { get; set; }
        public int ClienteId { get; set; }
        public int ViviendaId { get; set; }
        public int AgenciaId { get; set; }
        public decimal Valor { get; set; }
        [JsonIgnore]

        public virtual AGEncia AGEncia { get; set; }
        [JsonIgnore]

        public virtual CLIente CLIente { get; set; }
        [JsonIgnore]

        public virtual VIVienda VIVienda { get; set; }
    }
}
